"""
Publication figures, generated as vector PDF from the CSV data layer.

Separating figures from simulations means the paper can be rebuilt in seconds
without rerunning ~1 h of Monte Carlo, and every plotted point is traceable to
a row in repo/data/.  Map-type figures that cannot be reduced to tabular data
(field maps, the differential-displacement map, the 2D atmosphere) are
regenerated by their own scripts; see make_maps.sh.
"""

import csv
import os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

DATA = "repo/data"
OUT = "repo/figures"
os.makedirs(OUT, exist_ok=True)

plt.rcParams.update({
    "font.size": 9,
    "axes.labelsize": 9,
    "axes.titlesize": 9,
    "legend.fontsize": 8,
    "xtick.labelsize": 8,
    "ytick.labelsize": 8,
    "axes.linewidth": 0.8,
    "lines.linewidth": 1.4,
    "pdf.fonttype": 42,          # embed TrueType, not Type 3: required by
    "ps.fonttype": 42,           # most publishers
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.02,
})

MU30 = 2.30          # GPa, theoretical shear strength


def load(name):
    """Read a CSV, skipping the leading comment line."""
    with open(os.path.join(DATA, name)) as f:
        lines = [l for l in f if not l.startswith("#")]
    r = csv.DictReader(lines)
    return list(r)


def save(fig, stem):
    for ext in ("pdf", "png"):
        fig.savefig(os.path.join(OUT, f"{stem}.{ext}"), dpi=300)
    plt.close(fig)
    print(f"  {stem}.pdf / .png")


# ------------------------------------------------------ Fig 2: edge depinning
def fig_edge_depinning():
    d = load("edge_depinning_vs_ageing.csv")
    th = np.array([float(r["theta"]) for r in d])
    tc = np.array([float(r["tau_c_GPa"]) for r in d])
    sd = np.array([float(r["tau_c_sd_GPa"]) for r in d])
    coh = np.array([float(r["tau_coherent_GPa"]) for r in d])

    a = load("atmosphere_solute_interaction.csv")
    om = np.array([float(r["omega_eV"]) for r in a])
    ta = np.array([float(r["tau_c_GPa"]) for r in a])
    sa = np.array([float(r["tau_c_sd_GPa"]) for r in a])

    vc = load("varvenne_curtin_reference.csv")
    vc_m = float([r for r in vc if "matched" in r["basis"]][0]["tau_y0_GPa"])

    fig, ax = plt.subplots(1, 2, figsize=(7.1, 3.0))

    ax[0].axhspan(MU30, 1e3, color="0.90", zorder=0)
    ax[0].errorbar(th, tc, yerr=sd, fmt="o-", capsize=3, color="tab:blue",
                   label="flexible line")
    ax[0].plot(th, coh, "s--", color="tab:red", ms=4,
               label="coherent trough, rigid")
    ax[0].axhline(vc_m, color="tab:green", ls=":",
                  label=rf"Varvenne–Curtin, {vc_m:.2f} GPa")
    ax[0].axhline(MU30, color="0.3", ls="-.", lw=1.1, label=r"$\mu/30$")
    ax[0].set_yscale("log")
    ax[0].set_ylim(0.06, 20)
    ax[0].set_xlabel(r"ageing fraction $\theta$")
    ax[0].set_ylabel(r"$\tau_c$ (0 K) [GPa]")
    ax[0].set_title(r"(a) edge dislocation, $N_z=128$")
    ax[0].legend(loc="lower right", frameon=False)

    ax[1].errorbar(om, ta, yerr=sa, fmt="o-", capsize=3, color="tab:purple")
    ax[1].axhline(ta[0], color="0.5", ls="--",
                  label=r"$J=0$ (Bernoulli)")
    ax[1].axhline(MU30, color="0.3", ls="-.", lw=1.1, label=r"$\mu/30$")
    for x, y, e in zip(om, ta, ta/ta[0]):
        if e > 1.05:
            ax[1].annotate(f"{e:.2f}×", (x, y), textcoords="offset points",
                           xytext=(4, -10), fontsize=7)
    ax[1].set_xlabel(r"interchange energy $\omega$ [eV]")
    ax[1].set_ylabel(r"$\tau_c$ (0 K) [GPa]")
    ax[1].set_title(r"(b) solute–solute interaction, $\theta=1$")
    ax[1].legend(frameon=False)

    for a_ in ax:
        a_.grid(alpha=0.25, lw=0.5)
    fig.tight_layout()
    save(fig, "fig2_edge_depinning")


# ------------------------------------------------------- Fig 3: convergence
def fig_convergence():
    d = load("convergence.csv")
    ll = load("line_length_scaling.csv")
    sc = load("realisation_scatter.csv")

    fig, ax = plt.subplots(1, 3, figsize=(7.1, 2.5))

    for k, m, lab in [("dx_grid", "o", r"$dx$ [$\AA$]"),
                      ("n_tau", "s", r"$n_\tau$"),
                      ("R_keep", "^", r"$R_{\rm keep}$ [$\AA$]")]:
        rows = [r for r in d if r["parameter"] == k]
        x = np.array([float(r["value"]) for r in rows])
        y = np.array([float(r["tau_c_GPa"]) for r in rows])
        ax[0].plot(x/x[np.argmin(np.abs(x - x.mean()))], y, m + "-", ms=4,
                   label=lab)
    ax[0].set_xscale("log")
    ax[0].set_xlabel("parameter / reference value")
    ax[0].set_ylabel(r"$\tau_c$ [GPa]")
    ax[0].set_title("(a) converged parameters")
    ax[0].legend(frameon=False)

    Nz = np.array([float(r["Nz"]) for r in ll])
    y = np.array([float(r["tau_c_GPa"]) for r in ll])
    e = np.array([float(r["sem_GPa"]) for r in ll])
    ax[1].errorbar(Nz, y, yerr=e, fmt="o", ms=4, capsize=2, color="tab:red")
    xf = np.linspace(Nz.min(), Nz.max(), 100)
    ax[1].plot(xf, 1.885 - 0.107*np.log(xf), "k--", lw=1.1,
               label=r"$1.885-0.107\ln N_z$")
    ax[1].set_xscale("log")
    ax[1].set_xlabel(r"$N_z$ (segments)")
    ax[1].set_ylabel(r"$\tau_c$ [GPa]")
    ax[1].set_title("(b) no plateau: weakest link")
    ax[1].legend(frameon=False)

    v = np.array([float(r["tau_c_GPa"]) for r in sc])
    n = np.arange(1, v.size + 1)
    run = np.array([v[:i].mean() for i in n])
    sem = np.array([v[:i].std(ddof=1)/np.sqrt(i) if i > 1 else np.nan
                    for i in n])
    ax[2].plot(n, run, "o-", ms=3, color="tab:blue")
    ax[2].fill_between(n, run - sem, run + sem, alpha=0.25)
    ax[2].axhline(v.mean(), color="k", ls="--", lw=0.9)
    ax[2].set_xlabel("realisations")
    ax[2].set_ylabel(r"$\tau_c$ [GPa]")
    ax[2].set_title(f"(c) scatter {100*v.std(ddof=1)/v.mean():.1f}\\%")

    for a_ in ax:
        a_.grid(alpha=0.25, lw=0.5)
    fig.tight_layout()
    save(fig, "fig3_convergence")


# ------------------------------------------------------- Fig 4: sensitivities
def fig_sensitivity():
    u = load("sensitivity_ucap.csv")
    o = load("sensitivity_omega_rel.csv")

    fig, ax = plt.subplots(1, 2, figsize=(7.1, 2.9))

    for field, th, c, m in [("aniso", "0.25", "tab:red", "o"),
                            ("iso", "0.25", "tab:orange", "s"),
                            ("aniso", "0.0", "tab:blue", "^")]:
        rows = [r for r in u if r["field"] == field
                and abs(float(r["theta"]) - float(th)) < 1e-9]
        if not rows:
            continue
        x = np.array([float(r["U_cap_eV"]) for r in rows])
        y = np.array([float(r["tau_c_GPa"]) for r in rows])
        e = np.array([float(r["tau_c_sd_GPa"]) for r in rows])
        ax[0].errorbar(x, y, yerr=e, fmt=m + "-", ms=4, capsize=2, color=c,
                       label=rf"{field}, $\theta$={float(th):g}")
    xf = np.linspace(0.3, 1.5, 50)
    ax[0].plot(xf, 1.234*(xf/0.70)**0.91, "k--", lw=1.0,
               label=r"$\propto U_{\rm cap}^{0.91}$")
    ax[0].set_xscale("log"); ax[0].set_yscale("log")
    ax[0].set_xlabel(r"core binding $U_{\rm cap}$ [eV]")
    ax[0].set_ylabel(r"$\tau_c$ [GPa]")
    ax[0].set_title("(a) core binding energy")
    ax[0].legend(frameon=False, loc="upper left")

    x = np.array([float(r["Omega_rel_A3"]) for r in o])
    y = np.array([float(r["tau_c_GPa"]) for r in o])
    e = np.array([float(r["tau_c_sd_GPa"]) for r in o])
    ax[1].errorbar(x, y, yerr=e, fmt="o-", ms=4, capsize=2, color="tab:purple")
    xf = np.linspace(7, 17, 50)
    ax[1].plot(xf, 1.190*(xf/11.45)**1.26, "k--", lw=1.0,
               label=r"$\propto \Omega_{\rm rel}^{1.26}$")
    ax[1].axvline(11.45, color="0.5", ls=":", lw=1.0,
                  label="hard-sphere estimate")
    ax[1].set_xscale("log"); ax[1].set_yscale("log")
    ax[1].set_xlabel(r"relaxation volume $\Omega_{\rm rel}$ [$\AA^3$]")
    ax[1].set_ylabel(r"$\tau_c$ [GPa]")
    ax[1].set_title("(b) relaxation volume")
    ax[1].legend(frameon=False)

    for a_ in ax:
        a_.grid(alpha=0.25, lw=0.5, which="both")
    fig.tight_layout()
    save(fig, "fig4_sensitivity")


# ------------------------------------------------- Fig 5: screw and the KMC
def fig_screw_kmc():
    s = load("screw_vs_edge.csv")
    k = load("kmc_flow_stress.csv")

    fig, ax = plt.subplots(1, 2, figsize=(7.1, 2.9))

    th = np.array([float(r["theta"]) for r in s])
    te = np.array([float(r["tau_c_edge_GPa"]) for r in s])
    ts = np.array([float(r["tau_c_screw_GPa"]) for r in s])
    ax[0].axhspan(MU30, 1e3, color="0.90", zorder=0)
    ax[0].plot(th, te, "o-", color="tab:blue", ms=4, label="edge")
    ax[0].plot(th, ts, "s-", color="tab:orange", ms=4,
               label="screw (upper bound)")
    ax[0].axhline(MU30, color="0.3", ls="-.", lw=1.1, label=r"$\mu/30$")
    ax[0].set_yscale("log"); ax[0].set_ylim(2e-4, 20)
    ax[0].set_xlabel(r"ageing fraction $\theta$")
    ax[0].set_ylabel(r"$\tau_c$ (0 K) [GPa]")
    ax[0].set_title(r"(a) the atmosphere does not pin the screw")
    ax[0].legend(frameon=False, loc="center right")

    T = np.array([float(r["T_K"]) for r in k])
    tp = np.array([float(r["tau_pure_GPa"]) for r in k])
    ta = np.array([float(r["tau_alloy_GPa"]) for r in k])
    ok = np.isfinite(tp) & (tp > 1e-3)
    ax[1].plot(T[ok], tp[ok], "o-", color="tab:blue", ms=4, label="pure Ta")
    ax[1].plot(T, ta, "s-", color="tab:red", ms=4, label="Ta + 2 at.\\% Lu")
    ax[1].set_yscale("log")
    ax[1].set_xlabel(r"$T$ [K]")
    ax[1].set_ylabel(r"$\tau_y$ [GPa]")
    ax[1].set_title(r"(b) kink-pair KMC: hardening at every $T$")
    ax[1].legend(frameon=False)

    for a_ in ax:
        a_.grid(alpha=0.25, lw=0.5, which="both")
    fig.tight_layout()
    save(fig, "fig5_screw_kmc")


# ------------------------------------------------------ Fig 6: kappa threshold
def fig_kappa():
    d = load("kappa_scan.csv")
    fig, ax = plt.subplots(1, 2, figsize=(7.1, 2.9))

    for T, c in [(150, "tab:blue"), (250, "tab:red")]:
        rows = [r for r in d if int(float(r["T_K"])) == T]
        x = np.array([float(r["kappa_eV"]) for r in rows])
        y = np.array([float(r["ratio"]) for r in rows])
        ax[0].plot(x, y, "o-", ms=4, color=c, label=f"$T$ = {T} K")
    ax[0].axhline(1.0, color="k", lw=1.1)
    ax[0].axvline(0.166, color="0.4", ls=":", lw=1.1)
    ax[0].annotate(r"$\kappa^*=0.17$ eV", (0.166, 30),
                   textcoords="offset points", xytext=(4, 0), fontsize=8)
    ax[0].fill_between([0, 0.30], 0.1, 1.0, color="tab:green", alpha=0.12)
    ax[0].text(0.012, 0.35, "softening", fontsize=8, color="tab:green")
    ax[0].set_yscale("log")
    ax[0].set_xlabel(r"chemical softening $\kappa$ [eV]")
    ax[0].set_ylabel(r"$\tau_y^{\rm alloy}/\tau_y^{\rm pure}$")
    ax[0].set_title("(a) threshold for softening")
    ax[0].legend(frameon=False)

    kb = 8.617333e-5
    sig = 0.0382
    Tf = np.linspace(40, 320, 300)
    ax[1].plot(Tf, 1000*sig**2/(2*kb*Tf), color="tab:purple",
               label=r"annealed, $\sigma^2/2k_BT$")
    N = 128
    q = 1000*sig*np.sqrt(2*np.log(N))
    ax[1].axhline(q, color="k", ls="--", lw=1.0,
                  label=r"quenched, $\sigma\sqrt{2\ln N}$")
    Tst = sig/np.sqrt(2*np.log(N))/kb
    ax[1].axvline(Tst, color="0.5", ls=":", lw=1.0,
                  label=rf"$T^*$ = {Tst:.0f} K")
    ax[1].axhline(1000*0.90*0.19, color="tab:red", ls="-.", lw=1.1,
                  label=r"$\kappa^*$ = 19\% of $2E_k$")
    ax[1].set_xlabel(r"$T$ [K]")
    ax[1].set_ylabel("barrier reduction [meV]")
    ax[1].set_title("(b) what disorder can and cannot supply")
    ax[1].legend(frameon=False, fontsize=7)

    for a_ in ax:
        a_.grid(alpha=0.25, lw=0.5)
    fig.tight_layout()
    save(fig, "fig6_kappa_threshold")


if __name__ == "__main__":
    print("building vector figures from repo/data/ ...")
    fig_edge_depinning()
    fig_convergence()
    fig_sensitivity()
    fig_screw_kmc()
    fig_kappa()
    print("done")
