r"""Produce a single self-contained .tex from preamble + body.

The modular main.tex / preamble.tex / body.tex split keeps formatting separate
from regenerated content, but arXiv and most journals prefer one file.  This
writes main_standalone.tex (English) and main_zh_standalone.tex (Chinese) with
the \input directives resolved in place.

Usage: python3 flatten.py [--zh]
"""
import sys

ZH = "--zh" in sys.argv
suffix = "_zh" if ZH else ""
pre = f"preamble{suffix}.tex"
body = f"body{suffix}.tex"
out = f"main{suffix}_standalone.tex"

banner = "\n".join([
    "% " + "=" * 68,
    "%  Self-contained source: preamble and body merged.",
    f"%  Generated by flatten.py -- edit manuscript{suffix}.md and rerun",
    f"%  build{suffix}.sh, not this file.",
    "%  Compile with xelatex, twice.  Figures are expected in ../figures/;",
    "%  for arXiv, copy them alongside and set \\graphicspath{{./}}.",
    "%  arXiv does not run BibTeX: submit main.bbl with this file.",
    "% " + "=" * 68,
    "", "",
])

doc = (banner
       + open(pre).read().rstrip()
       + "\n\n\\begin{document}\n\\maketitle\n\n"
       + open(body).read()
       + "\n\\bibliographystyle{unsrtnat}\n\\bibliography{references}\n"
       + "\\end{document}\n")
open(out, "w").write(doc)
print(f"{out}: {doc.count(chr(10))} lines, {len(doc)} bytes")
